#!/usr/bin/env python3
"""Generate AGENTS.md — a single-file digest of every rule.

AGENTS.md is the vendor-neutral instruction format read natively by Codex,
Cursor, Copilot, Gemini CLI, Aider, Windsurf, Zed and others. Those tools have
no on-demand skill loading, so they need one compact file rather than seven
progressive-disclosure skills.

    python3 tools/build_agents_md.py

Regenerate whenever a rule changes. CI checks the file is current.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
REPO_URL = "https://github.com/Kaguara/emerging-market-skills"

HEADER = """# Building for emerging markets

<!-- Generated by tools/build_agents_md.py. Do not edit by hand. -->

Drop this file at the root of your project. Every rule below is a constraint for
software used on entry-level devices, over intermittent and expensive
connections, by people whose first computer is the phone in their hand.

Full guidance, worked code, and runnable validators: {url}

## The design target

Unless told otherwise, assume **tier C**: an entry-level Android phone with 1–2GB
of RAM shared with the OS, a CPU roughly a quarter as fast as a current flagship,
storage permanently near full, an ageing battery, on congested 3G with frequent
handover, paid for from a prepaid bundle bought in small increments.

## The four constraints

- **Network** — not slow, but intermittent, ambiguous, and dishonest. Requests
  that neither succeed nor fail. Connectivity flags reporting a live link that
  carries no traffic to your origin.
- **Device** — memory and CPU that fall off cliffs rather than degrading
  smoothly. Your process is a candidate for termination whenever it backgrounds.
- **Cost** — two meters running: yours per SMS, per API call, per token; theirs
  per megabyte, prepaid.
- **Interface** — read in a language with longer words than English, sometimes by
  someone using a smartphone for the first time.

## How to apply this

Severity means: **critical** — the product does not work for the target user.
**warning** — measurable degradation. **advisory** — a better default.

When you flag something, cite the rule ID. When something is wrong and no rule
covers it, say so and label it judgment rather than inventing a citation.

"""

FOOTER = """
---

## Before you claim any of this is verified

Static rules find structure, not truth. The device finds the truth:

- Measure the cold-cache first visit on a real entry-level device, not a warm
  reload on a developer machine.
- Kill the process mid-flow (`adb shell am kill <package>`) and confirm the
  user's work survived.
- Throttle to ~400kbps with 400ms RTT and drop the connection *mid-request* —
  that is the case that finds bugs, not airplane mode.
- Segment every metric by device tier. A p50 pooling flagship and entry-level
  users describes a device population that does not exist.

Rules carry evidence tags in the source repository — field (observed shipping a
product), published (research), or vendor (platform documentation). Critical
rules cannot be merged without one.

{url}
"""

ORDER = [
    "emerging-market-review",
    "network-resilience",
    "payload-budgets",
    "low-end-device-performance",
    "integration-cost-modeling",
    "localization-and-literacy-ux",
    "identity-and-onboarding",
]


def main() -> None:
    out = [HEADER.format(url=REPO_URL)]
    total = 0

    dirs = sorted(
        (d for d in (REPO / "skills").iterdir() if d.is_dir()),
        key=lambda d: ORDER.index(d.name) if d.name in ORDER else 99,
    )

    for skill_dir in dirs:
        rules_path = skill_dir / "rules.yml"
        skill_md = skill_dir / "SKILL.md"
        if not rules_path.exists():
            continue

        doc = yaml.safe_load(rules_path.read_text(encoding="utf-8"))
        title = skill_dir.name.replace("-", " ").capitalize()

        # First line of the "## The constraint" section, as a one-line summary.
        summary = ""
        if skill_md.exists():
            lines = skill_md.read_text(encoding="utf-8").splitlines()
            for i, line in enumerate(lines):
                if line.startswith("## The constraint"):
                    summary = " ".join(lines[i + 2:i + 4]).strip()
                    break

        out.append(f"## {title}\n")
        if summary:
            out.append(f"{summary}\n")
        out.append("| ID | Rule | Severity |")
        out.append("|---|---|---|")
        for rule in doc.get("rules", []):
            text = " ".join(str(rule["rule"]).split())
            out.append(f"| {rule['id']} | {text} | {rule['severity']} |")
            total += 1
        out.append("")

    out.append(FOOTER.format(url=REPO_URL))
    target = REPO / "AGENTS.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"AGENTS.md: {total} rules across {len(dirs)} skills, "
          f"{len(target.read_text().splitlines())} lines")


if __name__ == "__main__":
    sys.exit(main())
